get_together/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from events import feeds, views as event_views

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("admin/", admin.site.urls),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path(
        "account/password_change/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "account/password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "account/password_reset/",
        views.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "account/password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "account/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "account/reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("searchables/", event_views.searchable_list, name="searchables"),
    path("api/places/", event_views.places_list),
    path("api/countries/", event_views.country_list),
    path("api/spr/", event_views.spr_list),
    path("api/cities/", event_views.city_list),
    path("api/find_city/", event_views.find_city),
    path("api/teams/", event_views.teams_list),
    path("api/org/<int:org_id>/", event_views.org_member_list),
    path("api/upcoming_events/", event_views.upcoming_events),
    path(
        "profile/+confirm_profile",
        views.setup_1_confirm_profile,
        name="setup-1-confirm-profile",
    ),
    path(
        "profile/+pick_categories",
        views.setup_2_pick_categories,
        name="setup-2-pick-categories",
    ),
    path("profile/+find_teams", views.setup_3_find_teams, name="setup-3-find-teams"),
    path(
        "profile/+attend_events",
        views.setup_4_attend_events,
        name="setup-4-attend-events",
    ),
    path("profile/+setup_complete", views.setup_complete, name="setup-complete"),
    path("profile/+edit", views.edit_profile, name="edit-profile"),
    path(
        "profile/+send_confirmation_email",
        views.user_send_confirmation_email,
        name="send-confirm-email",
    ),
    path(
        "profile/+confirm_email/<str:confirmation_key>",
        views.user_confirm_email,
        name="confirm-email",
    ),
    path(
        "profile/+confirm_notifications",
        views.user_confirm_notifications,
        name="confirm-notifications",
    ),
    path("profile/<int:user_id>/", views.show_profile, name="show-profile"),
    path(
        "profile/<str:account_secret>.ics",
        feeds.UserEventsCalendar(),
        name="user-event-ical",
    ),
    path("profile/+add-speaker", views.add_speaker, name="add-speaker"),
    path("speaker/<int:speaker_id>/", views.show_speaker, name="show-speaker"),
    path("speaker/<int:speaker_id>/+edit", views.edit_speaker, name="edit-speaker"),
    path(
        "speaker/<int:speaker_id>/+delete", views.delete_speaker, name="delete-speaker"
    ),
    path("profile/+talks", views.list_user_talks, name="user-talks"),
    path("profile/+add-talk", views.add_talk, name="add-talk"),
    path("talk/<int:talk_id>/", views.show_talk, name="show-talk"),
    path("talk/<int:talk_id>/+edit", views.edit_talk, name="edit-talk"),
    path("talk/<int:talk_id>/+delete", views.delete_talk, name="delete-talk"),
    path("events/", views.events_list, name="events"),
    path("events/all/", views.events_list_all, name="all-events"),
    path("teams/", views.teams_list, name="teams"),
    path("teams/all/", views.teams_list_all, name="all-teams"),
    path("team/<int:team_id>/", views.show_team_by_id, name="show-team"),
    path("team/<int:team_id>/+edit/", views.edit_team, name="edit-team"),
    path("team/<int:team_id>/+join/", event_views.join_team, name="join-team"),
    path("team/<int:team_id>/+leave/", event_views.leave_team, name="leave-team"),
    path("team/<int:team_id>/+delete/", views.delete_team, name="delete-team"),
    path("team/<int:team_id>/+members/", views.manage_members, name="manage-members"),
    path(
        "team/<int:team_id>/+change_role/<int:profile_id>/",
        views.change_member_role,
        name="change-member-role",
    ),
    path("team/<int:team_id>/+invite/", views.invite_members, name="invite-members"),
    path(
        "team/invite/<int:invite_id>/+resend/",
        views.resend_member_invite,
        name="resend-member-invite",
    ),
    path(
        "team/+accept_invite/<str:invite_key>/",
        views.confirm_request_to_join_team,
        name="accept-invite-to-join-team",
    ),
    path(
        "team/<int:team_id>/events.ics",
        feeds.TeamEventsCalendar(),
        name="team-event-ical",
    ),
    path(
        "team/<int:team_id>/<str:account_secret>/events.ics",
        feeds.PrivateTeamEventsCalendar(),
        name="private-team-event-ical",
    ),
    path("+create-team/", views.start_new_team, name="create-team"),
    path("team/<int:team_id>/+define/", views.define_new_team, name="define-team"),
    path(
        "team/+create-event/",
        views.create_event_team_select,
        name="create-event-team-select",
    ),
    path("team/<int:team_id>/+create-event/", views.create_event, name="create-event"),
    path("+new-event/", views.new_event_start, name="new-event-start"),
    path(
        "events/<int:event_id>/+new-event-place/",
        views.new_event_add_place,
        name="new-event-add-place",
    ),
    path(
        "events/<int:event_id>/+new-event-details/",
        views.new_event_add_details,
        name="new-event-add-details",
    ),
    path(
        "events/<int:event_id>/+new-event-team/",
        views.new_event_add_team,
        name="new-event-add-team",
    ),
    path("events/<int:event_id>/+edit/", views.edit_event, name="edit-event"),
    path("events/<int:event_id>/+host/", views.change_event_host, name="change-team"),
    path("events/<int:event_id>/+attend/", views.attend_event, name="attend-event"),
    path(
        "events/<int:event_id>/+attended/", views.attended_event, name="attended-event"
    ),
    path(
        "events/<int:event_id>/+attendees/",
        views.manage_attendees,
        name="manage-attendees",
    ),
    path(
        "events/<int:event_id>/+sponsors/",
        views.manage_event_sponsors,
        name="manage-event-sponsors",
    ),
    path("events/<int:event_id>/+sponsor/", views.sponsor_event, name="sponsor-event"),
    path(
        "events/<int:event_id>/+invite/",
        views.invite_attendees,
        name="invite-attendees",
    ),
    path("events/<int:event_id>/+delete/", views.delete_event, name="delete-event"),
    path("events/<int:event_id>/+cancel/", views.cancel_event, name="cancel-event"),
    path("events/<int:event_id>/+restore/", views.restore_event, name="restore-event"),
    path(
        "events/<int:event_id>/+add_place/", views.add_place_to_event, name="add-place"
    ),
    path("events/<int:event_id>/+comment/", views.comment_event, name="comment-event"),
    path("comment/<int:comment_id>/+edit/", views.edit_comment, name="comment-edit"),
    path(
        "comment/<int:comment_id>/+delete/", views.delete_comment, name="comment-delete"
    ),
    path(
        "events/<int:event_id>/+photo/", views.add_event_photo, name="add-event-photo"
    ),
    path(
        "photo/<int:photo_id>/+remove/",
        views.remove_event_photo,
        name="remove-event-photo",
    ),
    path(
        "events/<int:event_id>/+propose-talk/",
        views.propose_event_talk,
        name="propose-event-talk",
    ),
    path(
        "events/<int:event_id>/+schedule-talks/",
        views.schedule_event_talks,
        name="schedule-event-talks",
    ),
    path(
        "events/<int:event_id>/<str:event_slug>/", views.show_event, name="show-event"
    ),
    path(
        "events/<int:event_id>/<str:event_slug>.ics",
        feeds.SingleEventCalendar(),
        name="single-event-ical",
    ),
    path("series/<int:series_id>/+edit/", views.edit_series, name="edit-series"),
    path("series/<int:series_id>/+delete/", views.delete_series, name="delete-series"),
    path(
        "series/<int:series_id>/+add_place/",
        views.add_place_to_series,
        name="add-place-to-series",
    ),
    path(
        "series/<int:series_id>/<str:series_slug>/",
        views.show_series,
        name="show-series",
    ),
    path("org/<str:org_slug>/", views.show_org, name="show-org"),
    path("org/<str:org_slug>/+edit/", views.edit_org, name="edit-org"),
    path(
        "team/<int:team_id>/+invite_to_join_org/",
        views.invite_to_join_org,
        name="invite-to-join-org",
    ),
    path(
        "org/invite/<int:invite_id>/+resend/",
        views.resend_org_invite,
        name="resend-org-invite",
    ),
    path(
        "org/<str:org_slug>/+request_to_join_org/",
        views.request_to_join_org,
        name="request-to-join-org",
    ),
    path(
        "org/+confirm_request/<str:request_key>/",
        views.confirm_request_to_join_org,
        name="confirm-request-to-join-org",
    ),
    path(
        "org/<str:org_slug>/+manage_teams/", views.manage_org_teams, name="manage-teams"
    ),
    path(
        "org/<str:org_slug>/+create-event/",
        views.create_common_event,
        name="create-common-event",
    ),
    path(
        "common/<int:event_id>/+create-event/",
        views.create_common_event_team_select,
        name="create-common-event-team-select",
    ),
    path(
        "common/<int:event_id>/+edit/",
        views.edit_common_event,

accounts/models.py
import datetime
import hashlib

from django.conf import settings
from django.contrib.auth.models import AnonymousUser, Group, User
from django.contrib.sites.models import Site
from django.db import models
from django.utils.crypto import get_random_string
from django.utils.translation import ugettext_lazy as _

import pytz


class Account(models.Model):
    " Store account information about a user "

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    acctname = models.CharField(_("Account Name"), max_length=150, blank=True)
    is_email_confirmed = models.BooleanField(default=False)

    has_completed_setup = models.BooleanField(default=False)
    setup_completed_date = models.DateTimeField(blank=True, null=True)

    badges = models.ManyToManyField("Badge", through="BadgeGrant")

    class Meta:
        ordering = ("user__username",)

    def setup_complete(self):
        self.has_completed_setup = True
        self.setup_completed_date = datetime.datetime.now()
        self.save()

    def new_confirmation_request(self):
        valid_for = getattr(settings, "EMAIL_CONFIRMAION_EXPIRATION_DAYS", 5)
        confirmation_key = get_random_string(length=32)
        return EmailConfirmation.objects.create(
            user=self.user,
            email=self.user.email,
            key=confirmation_key,
            expires=datetime.datetime.now() + datetime.timedelta(days=valid_for),
        )

    def confirm_email(self, confirmation_key):
        try:
            confirmation_request = EmailConfirmation.objects.get(
                user=self.user,
                email=self.user.email,
                key=confirmation_key,
                expires__gt=datetime.datetime.now(),
            )
            if confirmation_request is not None:
                self.is_email_confirmed = True
                self.save()
                confirmation_request.delete()
                return True
        except Exception as e:
            print(e)
            return False

    def remaining_emails_allowed(self):
        recently_sent = EmailRecord.objects.filter(
            sender=self.user,
            when__gte=datetime.datetime.now() - datetime.timedelta(hours=24),
        ).count()
        if recently_sent < settings.ALLOWED_EMAILS_PER_DAY:
            return settings.ALLOWED_EMAILS_PER_DAY - recently_sent
        else:
            return 0

    def __str__(self):
        try:
            if self.acctname:
                return self.acctname
            return "%s" % self.user.username
        except:
            return _("Unknown Account")


def _getUserAccount(self):
    if not self.is_authenticated:
        return Account()

    profile, created = Account.objects.get_or_create(user=self)

    if created:
        if self.first_name:
            if self.last_name:
                profile.acctname = "%s %s" % (self.first_name, self.last_name)
            else:
                profile.acctname = self.first_name

        profile.save()

    return profile


def _getAnonAccount(self):
    return Account(acctname=_("Anonymous User"))


User.account = property(_getUserAccount)
AnonymousUser.account = property(_getAnonAccount)


class EmailConfirmation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.CharField(max_length=256)
    key = models.CharField(max_length=256)
    expires = models.DateTimeField()


class Badge(models.Model):
    name = models.CharField(_("Badge Name"), max_length=64, blank=False, null=False)
    img_url = models.URLField(_("Badge Image"), blank=False, null=False)

    def __str__(self):
        return self.name


class BadgeGrant(models.Model):
    badge = models.ForeignKey(Badge, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)

    expires = models.DateTimeField()
    granted_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return "%s for %s" % (self.badge.name, self.account.acctname)


class EmailRecord(models.Model):
    """
    Model to store all the outgoing emails.
    """

    when = models.DateTimeField(null=False, auto_now_add=True)
    sender = models.ForeignKey(
        User,
        related_name="sent_messages",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )
    recipient = models.ForeignKey(
        User,
        related_name="recv_messages",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )
    email = models.EmailField(null=False, blank=False)
    subject = models.CharField(null=False, max_length=128)
    body = models.TextField(null=False, max_length=1024)
    ok = models.BooleanField(null=False, default=True)

get_together/views/places.py
import datetime

from django.contrib import messages
from django.contrib.auth import logout as logout_user
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import ugettext_lazy as _

import simplejson
from events.forms import NewPlaceForm
from events.models.events import Attendee, Event, Place
from events.models.profiles import Member, Team, UserProfile


# Create your views here.
def places_list(request, *args, **kwargs):
    places = Place.objects.all()
    context = {"places_list": places}
    return render(request, "get_together/places/list_places.html", context)


def show_place(request, place_id):
    place = get_object_or_404(Place, id=place_id)
    context = {
        "place": place,
        "event_list": Event.objects.filter(
            place=place, team__access=Team.PUBLIC
        ).order_by("-start_time"),
    }
    return render(request, "get_together/places/show_place.html", context)


def create_place(request):
    if request.method == "GET":
        form = NewPlaceForm()

        context = {"place_form": form}
        return render(request, "get_together/places/create_place.html", context)
    elif request.method == "POST":
        form = NewPlaceForm(request.POST)
        if form.is_valid():
            new_place = form.save()
            return redirect("places")
        else:
            context = {"place_form": form}
            return render(request, "get_together/places/create_place.html", context)
    else:
        return redirect("home")

get_together/views/utils.py
import math

from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from events.location import get_client_ip, get_geoip
from events.models import Team

KM_PER_DEGREE_LAT = 110.574
KM_PER_DEGREE_LNG = 111.320  # At the equator
DEFAULT_NEAR_DISTANCE = 100  # kilometeres


def get_nearby_teams(request, near_distance=DEFAULT_NEAR_DISTANCE):
    g = get_geoip(request)
    if g.latlng is None or g.latlng[0] is None or g.latlng[1] is None:
        print("Could not identify latlng from geoip")
        return Team.objects.none()
    try:
        minlat = g.latlng[0] - (near_distance / KM_PER_DEGREE_LAT)
        maxlat = g.latlng[0] + (near_distance / KM_PER_DEGREE_LAT)
        minlng = g.latlng[1] - (
            near_distance / (KM_PER_DEGREE_LNG * math.cos(math.radians(g.latlng[0])))
        )
        maxlng = g.latlng[1] + (
            near_distance / (KM_PER_DEGREE_LNG * math.cos(math.radians(g.latlng[0])))
        )

        near_teams = Team.public_objects.filter(
            city__latitude__gte=minlat,
            city__latitude__lte=maxlat,
            city__longitude__gte=minlng,
            city__longitude__lte=maxlng,
        )
        return near_teams
    except Exception as e:
        print("Error looking for local teams: ", e)
        return Team.objects.none()

get_together/templates/get_together/orgs/accept_invite.html
{% extends "get_together/base.html" %}
{% load static i18n %}

{% block content %}
<h2>{% blocktrans with team_name=team.name org_name=org.name %}<b>{{team_name}}</b> has been invited to join <b>{{org_name}}</b>{% endblocktrans %}</h2>
<p>{% trans "Would you like to join this organization?" %}</p>
<form action="{% url "confirm-request-to-join-org" invite.request_key %}" method="post">
{% csrf_token %}
{% include "events/org_invite_form.html" %}
	<br />
<button type="submit" class="btn btn-primary">{% trans "Accept" %}</button>
<a class="btn btn-secondary" href="{% url 'show-team' team.id %}">{% trans "Decline" %}</a>
</form>
{% endblock %}

get_together/templates/get_together/orgs/accept_request.html
{% extends "get_together/base.html" %}
{% load static i18n %}

{% block content %}
<h2>{% blocktrans with team_name=team.name org_name=org.name %}<b>{{team_name}}</b> has asked to join <b>{{org_name}}</b>{% endblocktrans %}</h2>
<p>{% trans "Would you like to add this team?" %}</p>
<form action="{% url "confirm-request-to-join-org" invite.request_key %}" method="post">
{% csrf_token %}
{% include "events/org_request_form.html" %}
	<br />
<button type="submit" class="btn btn-primary">{% trans "Accept" %}</button>
<a class="btn btn-secondary" href="{% url 'show-org' org.slug %}">{% trans "Decline" %}</a>
</form>
{% endblock %}

get_together/templates/get_together/orgs/create_common_event.html
{% extends "get_together/base.html" %}
{% load static i18n %}

{% block content %}
<h2>{% blocktrans with org_name=org.name %}Plan a <strong>{{org_name}}</strong> event{% endblocktrans %}</h2>
<form action="{% url "create-common-event" org.slug%}" method="post">
{% csrf_token %}
<div class="form-group">
{% include "events/event_form.html" %}
	<br />
<button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
</div>
</form>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/jquery-ui-lookup.js' %}"></script>
<script type="text/javascript">
$(document).ready(function(){

    $.datepicker.setDefaults({
        showOn: 'focus',
        dateFormat: 'yy-mm-dd',
    });

    $("#id_start_time_0").datepicker({altField: "#id_end_time_0", altFormat: "yy-mm-dd"});

    $("#id_end_time_0").datepicker();

    $("#id_continent").selectmenu();

    $("#country_select").lookup({
        search: function(searchText, callback) {
        if (searchText.length < 3) return callback(searchText, []);
            $.getJSON("/api/countries/?q="+searchText, function(data) {
                var m = this.url.match(/q=([^&]+)/);
                var q = "";
                if (m && m.length > 0) {
                    q = this.url.match(/q=([^&]+)/)[1]
                }

                return callback(q, data);
            });
        }
    })

    $("#spr_select").lookup({
        search: function(searchText, callback) {
        if (searchText.length < 3) return callback(searchText, []);
            $.getJSON("/api/spr/?q="+searchText, function(data) {
                var m = this.url.match(/q=([^&]+)/);
                var q = "";
                if (m && m.length > 0) {
                    q = this.url.match(/q=([^&]+)/)[1]
                }

                return callback(q, data);
            });
        }
    })

    $("#city_select").lookup({
        search: function(searchText, callback) {
        if (searchText.length < 3) return callback(searchText, []);
            $.getJSON("/api/cities/?q="+searchText, function(data) {
                var m = this.url.match(/q=([^&]+)/);
                var q = "";
                if (m && m.length > 0) {
                    q = this.url.match(/q=([^&]+)/)[1]
                }

                return callback(q, data);
            });
        }
    })

    $("#place_select").lookup({
        search: function(searchText, callback) {
        if (searchText.length < 3) return callback(searchText, []);
            $.getJSON("/api/places/?q="+searchText, function(data) {
                var m = this.url.match(/q=([^&]+)/);
                var q = "";
                if (m && m.length > 0) {
                    q = this.url.match(/q=([^&]+)/)[1]
                }

                return callback(q, data);
            });
        }
    })

    $("#id_category").selectmenu();
    $("#id_tz").selectmenu();

    $("#id_start_time_1").selectmenu({width: 150});
    $("#id_end_time_1").selectmenu({width: 150});
});

</script>
{% endblock %}

get_together/templates/get_together/orgs/create_common_event_team_select.html
{% extends "get_together/base.html" %}
{% load static i18n %}

{% block styles %}
    <link href="{% static 'css/bootstrap-album.css' %}" rel="stylesheet"/>

{% endblock %}

{% block content %}
<h2>{% trans "Select which team:" %}</h2>
<div class="container">
  <div class="row">
{% for team in teams %}
    <div class="col-md-4">
      <div class="card mb-4 box-shadow">
        <div class="card-banner">
          <a href="{% url 'show-team-by-slug' team.slug %}">
          <img class="card-img-top" src="{{team.card_img_url}}" alt="{{team.name}}">
          </a>
          <p class="card-title">{{team.name}}</p>
        </div>
        <div class="card-body">
          <p class="card-text"><strong>{{team.city}}</strong></p>
          <div class="d-flex justify-content-between align-items-center">
            <small class="text-muted">{% blocktrans count member_count=team.members.count %}{{ members_count }} member{% plural %}{{ members_count }} members{% endblocktrans %}</small>
            <div class="btn-group">
                <a class="btn btn-success" href="{% url 'create-event' team.id %}?common={{common_event_id}}">{{ theme.text_labels.host_event }}</a></span>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endfor %}
  </div>
</div>
{% endblock %}

get_together/templates/get_together/orgs/edit_org.html
{% extends "get_together/base.html" %}
{% load static i18n %}

{% block content %}
<h2>{%blocktrans with org_name=org.name %}Update <b>{{org_name}}</b>{% endblocktrans %}</h2>
<form action="{% url "edit-org" org.slug %}" enctype="multipart/form-data" method="post">
{% csrf_token %}
{% include "events/org_form.html" %}
	<br />
<button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
</form>
{% endblock %}

get_together/templates/get_together/orgs/invite_to_join.html
{% extends "get_together/base.html" %}
{% load static i18n %}

{% block content %}
<h2>{% blocktrans with team_name=team.name %}Invite: {{team_name}}{% endblocktrans %}</h2>
<p>{% trans "Select which of your organizations you would like to invite this team to." %}</p>
<form action="{% url "invite-to-join-org" team.id %}" enctype="multipart/form-data" method="post">
{% csrf_token %}
{% include "events/org_invite_form.html" %}
	<br />
<button type="submit" class="btn btn-primary">{% trans "Invite" %}</button>
</form>
{% endblock %}


{% block javascript %}
<script type="text/javascript">
$(document).ready(function(){

    $("#id_organization").selectmenu();
});

</script>
{% endblock %}

get_together/templates/get_together/orgs/manage_teams.html
{% extends "get_together/base.html" %}
{% load markup tz i18n %}

{% block add_to_title %} | {{org.name}}{% endblock %}


{% block content %}

{% if requests %}
    <div class="alerts">
        <div class="alert alert-success">
            {% blocktrans count requests=requests.count %}
            You have <a href="#requests">{{ requests }} request</a> to join your Org!
            {% plural %}
            You have <a href="#requests">{{ requests }} requests</a> to join your Org!
            {% endblocktrans %}
        </div>
    </div>
{% endif %}

<div class="fluid-container">
    <div class="row">
        <div class="col-sm-9">
            <h2><a href="{% url 'show-org' org.slug %}">{{ org.name }}</a> {% trans "Teams" %}</h2>

            <table class="table">
            <tr>
                <th colspan="2">{% trans "Team" %}</th>
                <th>{% trans "Contact" %}</th>
                <th>{% trans "Location" %}</th>
                <th>{% trans "Members" %}</th>
            </tr>
            {% for team in teams %}
            <tr>
                <td><img class="rounded" src="{{team.card_img_url}}" height="64px"></td>
                <td><a href="{% url 'show-team-by-slug' team.slug %}">{{team.name}}</a></td>
                <td>
                    <a href="javascript:contact_team({{team.id}});" class="fa fa-envelope" title="Contact"></a>
                </td>
                <td>
                    {{team.city.short_name}}
                </td>
                <td>
                        {{team.members.count}}
                </td>
            </tr>
            {% endfor %}
            </table>

            {% if requests %}
            <h3 id="requests">{% trans "Requests to join" %}</h3>
            <table class="table">
            <tr>
                <th colspan="2">{% trans "Team" %}</th>
                <th>{% trans "Location" %}</th>
                <th>{% trans "Owner" %}</th>
                <th>{% trans "Requested" %}</th>
                <th></th>
            </tr>
            {% for req in requests %}
            <tr>
                <td><img class="rounded" src="{{req.team.card_img_url}}" height="64px"></td>
                <td><a href="{% url 'show-team-by-slug' req.team.slug %}">{{req.team.name}}</a></td>
                <td>
                    {{req.team.city.short_name}}
                </td>
                <td>
                        <a href="{% url 'show-profile' req.team.owner_profile.id %}">{{req.team.owner_profile}}</a>
                        {% if req.team.owner_profile.user.account.is_email_confirmed %}
                            <i class="fa fa-envelope" title="Email Confirmed"></i>
                        {% endif %}
                </td>
                <td>
                    {{req.requested_date|date}}
                </td>
                <td>
                    <a class="btn btn-sm btn-success" href="{% url 'confirm-request-to-join-org' req.request_key %}">{% trans "Confirm" %}</a>
                </td>
                </tr>
            {% endfor %}
            </table>
            {% endif %}

            {% if invites %}
            <h3>{% trans "Pending invitations" %}</h3>
            <table class="table">
            <tr>
                <th colspan="2">{% trans "Team" %}</th>
                <th>{% trans "Location" %}</th>
                <th>{% trans "Owner" %}</th>
                <th>{% trans "Invited" %}</th>
            </tr>
            {% for req in invites %}
            <tr>
                <td><img class="rounded" src="{{req.team.card_img_url}}" height="64px"></td>
                <td><a href="{% url 'show-team-by-slug' req.team.slug %}">{{req.team.name}}</a></td>
                <td>
                    {{req.team.city.short_name}}
                </td>
                <td>
                        <a href="{% url 'show-profile' req.team.owner_profile.id %}">{{req.team.owner_profile}}</a>
                        {% if req.team.owner_profile.user.account.is_email_confirmed %}
                            <i class="fa fa-envelope text-muted" title="Email Confirmed"></i>
                        {% endif %}
                </td>
                <td>
                    {{req.requested_date}}
                </td>
                <td>
                    {% if req.can_resend %}
                    <a href="{% url 'resend-org-invite' req.id %}?csrftoken={{csrf_token}}" >Resend</a>
                    {% endif %}
                </td>
                </tr>
            {% endfor %}
            </table>
            {% endif %}
        </div>

        <div class="col-sm-3">
            <div class="container">
            <h4>{% trans "Contact" %}</h4><hr/>
                <div class="row">
                    <div class="col">
                        <form action="{% url 'manage-teams' org.slug %}" method="POST">
                            {% csrf_token %}
                            {{ contact_form.as_p }}
                            <button type="submit" class="btn btn-primary btn-sm">{% trans "Send" %}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
$(document).ready(function(){
    $("#id_to").selectmenu();
});

function contact_team(team_id) {
    $("#id_to").val(team_id);
    $("#id_to").selectmenu("refresh");
    $("#id_body").focus();
}
</script>
{% endblock %}

get_together/templates/get_together/orgs/request_to_join.html
{% extends "get_together/base.html" %}
{% load static i18n %}

{% block content %}
<h2>{% blocktrans with org_name=org.name %}Request to join: {{org_name}}{% endblocktrans %}</h2>
<p>{% trans "Select which of your teams you would like to add to this organization." %}</p>
<form action="{% url "request-to-join-org" org.slug %}" enctype="multipart/form-data" method="post">
{% csrf_token %}
{% include "events/org_request_form.html" %}
	<br />
<button type="submit" class="btn btn-primary">{% trans "Request" %}</button>
</form>
{% endblock %}


{% block javascript %}
<script type="text/javascript">
$(document).ready(function(){

    $("#id_team").selectmenu();
});

</script>
{% endblock %}