get_together/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from events import feeds, views as event_views

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("admin/", admin.site.urls),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path(
        "account/password_change/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "account/password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "account/password_reset/",
        views.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "account/password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "account/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "account/reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("searchables/", event_views.searchable_list, name="searchables"),
    path("api/places/", event_views.places_list),
    path("api/countries/", event_views.country_list),
    path("api/spr/", event_views.spr_list),
    path("api/cities/", event_views.city_list),
    path("api/find_city/", event_views.find_city),
    path("api/teams/", event_views.teams_list),
    path("api/org/<int:org_id>/", event_views.org_member_list),
    path("api/upcoming_events/", event_views.upcoming_events),
    path(
        "profile/+confirm_profile",
        views.setup_1_confirm_profile,
        name="setup-1-confirm-profile",
    ),
    path(
        "profile/+pick_categories",
        views.setup_2_pick_categories,
        name="setup-2-pick-categories",
    ),
    path("profile/+find_teams", views.setup_3_find_teams, name="setup-3-find-teams"),
    path(
        "profile/+attend_events",
        views.setup_4_attend_events,
        name="setup-4-attend-events",
    ),
    path("profile/+setup_complete", views.setup_complete, name="setup-complete"),
    path("profile/+edit", views.edit_profile, name="edit-profile"),
    path(
        "profile/+send_confirmation_email",
        views.user_send_confirmation_email,
        name="send-confirm-email",
    ),
    path(
        "profile/+confirm_email/<str:confirmation_key>",
        views.user_confirm_email,
        name="confirm-email",
    ),
    path(
        "profile/+confirm_notifications",
        views.user_confirm_notifications,
        name="confirm-notifications",
    ),
    path("profile/<int:user_id>/", views.show_profile, name="show-profile"),
    path(
        "profile/<str:account_secret>.ics",
        feeds.UserEventsCalendar(),
        name="user-event-ical",
    ),
    path("profile/+add-speaker", views.add_speaker, name="add-speaker"),
    path("speaker/<int:speaker_id>/", views.show_speaker, name="show-speaker"),
    path("speaker/<int:speaker_id>/+edit", views.edit_speaker, name="edit-speaker"),
    path(
        "speaker/<int:speaker_id>/+delete", views.delete_speaker, name="delete-speaker"
    ),
    path("profile/+talks", views.list_user_talks, name="user-talks"),
    path("profile/+add-talk", views.add_talk, name="add-talk"),
    path("talk/<int:talk_id>/", views.show_talk, name="show-talk"),
    path("talk/<int:talk_id>/+edit", views.edit_talk, name="edit-talk"),
    path("talk/<int:talk_id>/+delete", views.delete_talk, name="delete-talk"),
    path("events/", views.events_list, name="events"),
    path("events/all/", views.events_list_all, name="all-events"),
    path("teams/", views.teams_list, name="teams"),
    path("teams/all/", views.teams_list_all, name="all-teams"),
    path("team/<int:team_id>/", views.show_team_by_id, name="show-team"),
    path("team/<int:team_id>/+edit/", views.edit_team, name="edit-team"),
    path("team/<int:team_id>/+join/", event_views.join_team, name="join-team"),
    path("team/<int:team_id>/+leave/", event_views.leave_team, name="leave-team"),
    path("team/<int:team_id>/+delete/", views.delete_team, name="delete-team"),
    path("team/<int:team_id>/+members/", views.manage_members, name="manage-members"),
    path(
        "team/<int:team_id>/+change_role/<int:profile_id>/",
        views.change_member_role,
        name="change-member-role",
    ),
    path("team/<int:team_id>/+invite/", views.invite_members, name="invite-members"),
    path(
        "team/invite/<int:invite_id>/+resend/",
        views.resend_member_invite,
        name="resend-member-invite",
    ),
    path(
        "team/+accept_invite/<str:invite_key>/",
        views.confirm_request_to_join_team,
        name="accept-invite-to-join-team",
    ),
    path(
        "team/<int:team_id>/events.ics",
        feeds.TeamEventsCalendar(),
        name="team-event-ical",
    ),
    path(
        "team/<int:team_id>/<str:account_secret>/events.ics",
        feeds.PrivateTeamEventsCalendar(),
        name="private-team-event-ical",
    ),
    path("+create-team/", views.start_new_team, name="create-team"),
    path("team/<int:team_id>/+define/", views.define_new_team, name="define-team"),
    path(
        "team/+create-event/",
        views.create_event_team_select,
        name="create-event-team-select",
    ),
    path("team/<int:team_id>/+create-event/", views.create_event, name="create-event"),
    path("+new-event/", views.new_event_start, name="new-event-start"),
    path(
        "events/<int:event_id>/+new-event-place/",
        views.new_event_add_place,
        name="new-event-add-place",
    ),
    path(
        "events/<int:event_id>/+new-event-details/",
        views.new_event_add_details,
        name="new-event-add-details",
    ),
    path(
        "events/<int:event_id>/+new-event-team/",
        views.new_event_add_team,
        name="new-event-add-team",
    ),
    path("events/<int:event_id>/+edit/", views.edit_event, name="edit-event"),
    path("events/<int:event_id>/+host/", views.change_event_host, name="change-team"),
    path("events/<int:event_id>/+attend/", views.attend_event, name="attend-event"),
    path(
        "events/<int:event_id>/+attended/", views.attended_event, name="attended-event"
    ),
    path(
        "events/<int:event_id>/+attendees/",
        views.manage_attendees,
        name="manage-attendees",
    ),
    path(
        "events/<int:event_id>/+sponsors/",
        views.manage_event_sponsors,
        name="manage-event-sponsors",
    ),
    path("events/<int:event_id>/+sponsor/", views.sponsor_event, name="sponsor-event"),
    path(
        "events/<int:event_id>/+invite/",
        views.invite_attendees,
        name="invite-attendees",
    ),
    path("events/<int:event_id>/+delete/", views.delete_event, name="delete-event"),
    path("events/<int:event_id>/+cancel/", views.cancel_event, name="cancel-event"),
    path("events/<int:event_id>/+restore/", views.restore_event, name="restore-event"),
    path(
        "events/<int:event_id>/+add_place/", views.add_place_to_event, name="add-place"
    ),
    path("events/<int:event_id>/+comment/", views.comment_event, name="comment-event"),
    path("comment/<int:comment_id>/+edit/", views.edit_comment, name="comment-edit"),
    path(
        "comment/<int:comment_id>/+delete/", views.delete_comment, name="comment-delete"
    ),
    path(
        "events/<int:event_id>/+photo/", views.add_event_photo, name="add-event-photo"
    ),
    path(
        "photo/<int:photo_id>/+remove/",
        views.remove_event_photo,
        name="remove-event-photo",
    ),
    path(
        "events/<int:event_id>/+propose-talk/",
        views.propose_event_talk,
        name="propose-event-talk",
    ),
    path(
        "events/<int:event_id>/+schedule-talks/",
        views.schedule_event_talks,
        name="schedule-event-talks",
    ),
    path(
        "events/<int:event_id>/<str:event_slug>/", views.show_event, name="show-event"
    ),
    path(
        "events/<int:event_id>/<str:event_slug>.ics",
        feeds.SingleEventCalendar(),
        name="single-event-ical",
    ),
    path("series/<int:series_id>/+edit/", views.edit_series, name="edit-series"),
    path("series/<int:series_id>/+delete/", views.delete_series, name="delete-series"),
    path(
        "series/<int:series_id>/+add_place/",
        views.add_place_to_series,
        name="add-place-to-series",
    ),
    path(
        "series/<int:series_id>/<str:series_slug>/",
        views.show_series,
        name="show-series",
    ),
    path("org/<str:org_slug>/", views.show_org, name="show-org"),
    path("org/<str:org_slug>/+edit/", views.edit_org, name="edit-org"),
    path(
        "team/<int:team_id>/+invite_to_join_org/",
        views.invite_to_join_org,
        name="invite-to-join-org",
    ),
    path(
        "org/invite/<int:invite_id>/+resend/",
        views.resend_org_invite,
        name="resend-org-invite",
    ),
    path(
        "org/<str:org_slug>/+request_to_join_org/",
        views.request_to_join_org,
        name="request-to-join-org",
    ),
    path(
        "org/+confirm_request/<str:request_key>/",
        views.confirm_request_to_join_org,
        name="confirm-request-to-join-org",
    ),
    path(
        "org/<str:org_slug>/+manage_teams/", views.manage_org_teams, name="manage-teams"
    ),
    path(
        "org/<str:org_slug>/+create-event/",
        views.create_common_event,
        name="create-common-event",
    ),
    path(
        "common/<int:event_id>/+create-event/",
        views.create_common_event_team_select,
        name="create-common-event-team-select",
    ),
    path(
        "common/<int:event_id>/+edit/",
        views.edit_common_event,

events/models/locale.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

import pytz
from rest_framework import serializers


class Language(models.Model):
    class Meta:
        ordering = ("name",)

    name = models.CharField(_("Language"), max_length=150, null=True)
    code = models.CharField(_("Language Code"), max_length=20, null=True)

    def __str__(self):
        return u"%s" % (self.name)


class Continent(models.Model):
    name = models.CharField(_("Name"), max_length=50)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return u"%s" % (self.name)


class Country(models.Model):
    name = models.CharField(_("Name"), max_length=100)
    code = models.CharField(_("Country Code"), max_length=8)
    continents = models.ManyToManyField(Continent)

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Countries"

    def __str__(self):
        return u"%s" % (self.name)

    @property
    def slug(self):
        if self.name is not None:
            return self.name.replace(",", "").replace(" ", "_")
        else:
            return "no_country"


class CountrySerializer(serializers.ModelSerializer):
    display = serializers.CharField(source="__str__", read_only=True)

    class Meta:
        model = Country
        fields = ("id", "name", "code", "display")


class SPR(models.Model):
    name = models.CharField(_("Name"), max_length=100)
    code = models.CharField(_("Admin Code"), max_length=8)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return u"%s, %s" % (self.name, self.country.name)

    @property
    def slug(self):
        if self.name is not None:
            return self.name.replace(",", "").replace(" ", "_")
        else:
            return "no_spr"


class SPRSerializer(serializers.ModelSerializer):
    display = serializers.CharField(source="__str__", read_only=True)

    class Meta:
        model = SPR
        fields = ("id", "name", "code", "country", "slug", "display")


class City(models.Model):
    class Meta:
        ordering = ("name",)
        verbose_name_plural = _("Cities")

    name = models.CharField(_("Name"), max_length=100)
    spr = models.ForeignKey(SPR, on_delete=models.CASCADE)
    tz = models.CharField(
        max_length=32,
        verbose_name=_("Default Timezone"),
        default="UTC",
        choices=[(tz, tz) for tz in pytz.all_timezones],
        blank=False,
        null=False,
        help_text=_("The most commonly used timezone for this Team."),
    )
    longitude = models.FloatField(
        help_text=_("Longitude in Degrees East"), null=True, blank=True
    )
    latitude = models.FloatField(
        help_text=_("Latitude in Degrees North"), null=True, blank=True
    )
    population = models.IntegerField(
        help_text=_("Population"), null=False, blank=False, default=0
    )

    @property
    def short_name(self):
        if self.spr.country.name == "United States":
            return u"%s, %s" % (self.name, self.spr.name)
        else:
            return u"%s, %s" % (self.name, self.spr.country.name)

    def __str__(self):
        return u"%s, %s, %s" % (self.name, self.spr.name, self.spr.country.name)

    @property
    def slug(self):
        if self.name is not None:
            return self.name.replace(",", "").replace(" ", "_")
        else:
            return "no_city"


class CitySerializer(serializers.ModelSerializer):
    display = serializers.CharField(source="__str__", read_only=True)

    class Meta:
        model = City
        fields = (
            "id",
            "name",
            "short_name",
            "spr",
            "tz",
            "latitude",
            "longitude",
            "slug",
            "display",
        )

totd/models.py
from django.conf import settings
from django.contrib.messages.constants import DEFAULT_TAGS, INFO
from django.contrib.sites.models import Site
from django.db import models
from django.utils import timezone


# Create your models here.
class Tip(models.Model):
    name = models.CharField(max_length=128, null=False, blank=False)
    text = models.TextField()
    level = models.SmallIntegerField(choices=DEFAULT_TAGS.items(), default=INFO)

    run_start = models.DateTimeField(default=timezone.now)
    run_end = models.DateTimeField(null=True, blank=True)

    view = models.CharField(max_length=256, blank=True, null=True)
    sites = models.ManyToManyField(Site)

    seen_by = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="seen_tips", blank=True
    )

    def tags(self):
        return settings.MESSAGE_TAGS[self.level]

    def __str__(self):
        return self.name

get_together/views/places.py
import datetime

from django.contrib import messages
from django.contrib.auth import logout as logout_user
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import ugettext_lazy as _

import simplejson
from events.forms import NewPlaceForm
from events.models.events import Attendee, Event, Place
from events.models.profiles import Member, Team, UserProfile


# Create your views here.
def places_list(request, *args, **kwargs):
    places = Place.objects.all()
    context = {"places_list": places}
    return render(request, "get_together/places/list_places.html", context)


def show_place(request, place_id):
    place = get_object_or_404(Place, id=place_id)
    context = {
        "place": place,
        "event_list": Event.objects.filter(
            place=place, team__access=Team.PUBLIC
        ).order_by("-start_time"),
    }
    return render(request, "get_together/places/show_place.html", context)


def create_place(request):
    if request.method == "GET":
        form = NewPlaceForm()

        context = {"place_form": form}
        return render(request, "get_together/places/create_place.html", context)
    elif request.method == "POST":
        form = NewPlaceForm(request.POST)
        if form.is_valid():
            new_place = form.save()
            return redirect("places")
        else:
            context = {"place_form": form}
            return render(request, "get_together/places/create_place.html", context)
    else:
        return redirect("home")

get_together/views/utils.py
import math

from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from events.location import get_client_ip, get_geoip
from events.models import Team

KM_PER_DEGREE_LAT = 110.574
KM_PER_DEGREE_LNG = 111.320  # At the equator
DEFAULT_NEAR_DISTANCE = 100  # kilometeres


def get_nearby_teams(request, near_distance=DEFAULT_NEAR_DISTANCE):
    g = get_geoip(request)
    if g.latlng is None or g.latlng[0] is None or g.latlng[1] is None:
        print("Could not identify latlng from geoip")
        return Team.objects.none()
    try:
        minlat = g.latlng[0] - (near_distance / KM_PER_DEGREE_LAT)
        maxlat = g.latlng[0] + (near_distance / KM_PER_DEGREE_LAT)
        minlng = g.latlng[1] - (
            near_distance / (KM_PER_DEGREE_LNG * math.cos(math.radians(g.latlng[0])))
        )
        maxlng = g.latlng[1] + (
            near_distance / (KM_PER_DEGREE_LNG * math.cos(math.radians(g.latlng[0])))
        )

        near_teams = Team.public_objects.filter(
            city__latitude__gte=minlat,
            city__latitude__lte=maxlat,
            city__longitude__gte=minlng,
            city__longitude__lte=maxlng,
        )
        return near_teams
    except Exception as e:
        print("Error looking for local teams: ", e)
        return Team.objects.none()

get_together/templates/get_together/new_event/add_place.html
{% extends "get_together/base.html" %}
{% load static i18n %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">

            <h2>{% trans "Choose your meeting place" %}</h2>
            <form action="{% url "new-event-add-place" event.id %}" method="post">
            {% csrf_token %}
            <input type="hidden" id="id_id" name="id" value="" />
            {% include "events/place_form.html" %}
	            <div class="fluid-layout" id="place-map"></div>
            <br />
            <button type="submit" class="btn btn-primary">{% trans "Add Place" %}</button>
            </form>
            <a class="btn btn-secondary" href="{% url 'new-event-add-details' event.id %}">{% trans "Skip" %}</a>
        </div>
        <div id="map" class="col-md-6"></div>
    </div>
</div>
{% endblock %}

{% block javascript %}
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key={{settings.GOOGLE_MAPS_API_KEY}}&libraries=places"></script>
<script type="text/javascript">
/*
 * jQuery Google Map Plugin 0.2.3
 * https://wiki.ubuntu.com/ubuntu-django-foundations/map
 * Requires jQuery 1.4.2
 *
 * Copyright 2011, Ronnie van den Crommenacker
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 */

(function ($) {
    $.fn.extend({
        selectLocation: function (options) {
            var defaults = {
                html_lng: null,
                html_lat: null,
                html_tz: null,
                html_country: null,
                html_continent: null,
                marker_icon: null,
                markers: [],
                html_addr: null,
                mapOptions: {
                    zoom: 12,
                    center: {lat: {{event.team.city.latitude}}, lng: {{event.team.city.longitude}}},
                    mapTypeId: google.maps.MapTypeId.ROADMAP,
                    mapTypeControl: false
                }
            };
            options = $.extend(defaults, options);

            function showPositionHTML(ll, map, google_place_id) {
                var geocoder = new google.maps.Geocoder();
                geocoder.geocode({'latLng': ll}, function(results, status) {
                    if (status == google.maps.GeocoderStatus.OK) {
                        if (results[0]) {
                            $('#id_address').val(results[0].formatted_address);
                            var name, city, spr, country = "";
                            $.each(results[0].address_components, function(){
                                if(this.types[0]=="country") {
                                    country = this.long_name
                                } else if(this.types[0]=="administrative_area_level_1"){
                                    spr = this.long_name
                                } else if(this.types[0]=="locality"){
                                    city = this.long_name
                                }
                            });
                            if (google_place_id != null) {
                                $("#id_name").val("")
                                $("#id_name").attr("placeholder", "Searching...")
                                var places = new google.maps.places.PlacesService(map);
                                places.getDetails({'placeId': google_place_id},
                                    function(result, status) {
                                        $("#id_name").val(result.name);
                                        $("#id_place_url").val(result.website);
                                    }
                                );
                            }
                            $.getJSON("/api/find_city/?country="+country+"&spr="+spr+"&city="+city,
                                function(json) {
                                    if (json.id) {
                                        var selectField = $("#city_select");
                                        selectField.empty();
                                        selectField.append('<option value="'+ json.id +'" selected>'+ json.display + '</option>');
                                        selectField.lookup("refresh");

                                        $("#id_tz").val(json.tz);
                                        $("#id_tz").selectmenu("refresh");
                                    }
                                }
                            );
                        }
                    }
                });

                if (options.html_lng && options.html_lat) {
                    if (ll.lat() != null && ll.lng() != null) {
                        options.html_lat.val(ll.lat());
                        options.html_lng.val(ll.lng());
                        if (options.html_tz && options.html_country && options.html_continent) {
                            $.getJSON("http://ws.geonames.org/timezoneJSON?lat=" + ll.lat() + "&lng=" + ll.lng(),
                                function(json) {
                                    $(options.html_tz).filter(function() {
                                        return $(this).text() == json.timezoneId;
                                    }).prop('selected', true);

                                    $(options.html_country).filter(function() {
                                        return $(this).text() == json.countryName;
                                    }).prop('selected', true);

                                    $.getJSON("http://ws.geonames.org/countryInfoJSON?country=" + json.countryCode,
                                        function(json) {
                                            if (typeof json.geonames[0].continentName !== "undefined") {
                                                $(options.html_continent).filter(function() {
                                                    return $(this).text() == json.geonames[0].continentName;
                                                }).prop('selected', true);
                                            }
                                        }
                                    );
                                }
                            );
                        }
                    }
                }


            }

            function setMarker(map, ll, google_place_id) {
                var marker = null;

                if (options.markers.length) {
                    marker = options.markers[0];
                    marker.setPosition(ll);
                    marker.setAnimation(google.maps.Animation.DROP);
                } else {
                    marker = new google.maps.Marker({
                        map: map,
                        position: ll,
                        draggable: true,
                        animation: google.maps.Animation.DROP
                    });
                    if (options.marker_icon) {
                        marker.icon = options.marker_icon;
                    }
                    options.markers.push(marker);
                    google.maps.event.addListener(options.markers[0], 'mouseup', function () {
                        showPositionHTML(marker.getPosition(), map, google_place_id);
                    });
                }

                map.setCenter(ll);
                showPositionHTML(marker.getPosition(), map, google_place_id);
            }

            return $(this).each(function (i, html_element) {
                map = new google.maps.Map($(html_element)[0], options.mapOptions),
                ll = null;

                google.maps.event.addListener(map, 'click', function (event) {
                    if (event.hasOwnProperty('placeId')) {
                        setMarker(map, event.latLng, event.placeId);
                    } else {
                        setMarker(map, event.latLng);
                    }
                });

                if (options.html_lat.val() && options.html_lng.val()) {
                    ll = new google.maps.LatLng(options.html_lat.val(), options.html_lng.val());
                    setMarker(map, ll);
                }

                $.getJSON("/api/places/", function(data) {
                    for (let place of data) {
                        var position = new google.maps.LatLng(place['latitude'], place['longitude'])
                        var marker = new google.maps.Marker({
                          position: position,
                          label: place['name'],
                          map: map,
                        });
                        google.maps.event.addListener(marker, 'click',function(event) {
                          $("#id_id").val(place['id']);
                          $("#id_name").val(place['name']);
                          showPositionHTML(this.position, map);
                        });
                    }
                    return;
                });
            });

        }
    });
}(jQuery));
$("#map").selectLocation({
    html_lat: $("#id_latitude"),
    html_lng: $("#id_longitude")
});
</script>

<script src="{% static 'js/jquery-ui-lookup.js' %}"></script>
<script type="text/javascript">
$(document).ready(function(){
    $("#city_select").lookup({
        search: function(searchText, callback) {
        if (searchText.length < 3) return callback(searchText, []);
            $.getJSON("/api/cities/?q="+searchText, function(data) {
                var m = this.url.match(/q=([^&]+)/);
                var q = "";
                if (m && m.length > 0) {
                    q = this.url.match(/q=([^&]+)/)[1]
                }

                return callback(q, data);
            });
        },
        select: function( event, ui ) {
          $("#id_tz").val(ui.data.tz);
          $("#id_tz").selectmenu("refresh");
        }
    })
    $("#id_tz").selectmenu();
});

</script>
{% endblock %}

get_together/templates/get_together/new_event/create_event.html
{% extends "get_together/base.html" %}
{% load static i18n %}

{% block content %}
<h2>{{ theme.actions.host_event.label }}</h2>

<form action="{% url "new-event-start" %}" method="post">
{% csrf_token %}
<div class="form-group">
{% include "events/event_form.html" %}
	<br />
<button type="submit" class="btn btn-primary">{% trans "Schedule event" %}</button>
</div>
</form>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
$(document).ready(function(){

    $.datepicker.setDefaults({
        showOn: 'focus',
        dateFormat: 'yy-mm-dd',
    });

    $("#id_start_time_0").datepicker({altField: "#id_end_time_0", altFormat: "yy-mm-dd"});

    $("#id_end_time_0").datepicker();

    $("#id_start_time_1").selectmenu({width: 150});
    $("#id_end_time_1").selectmenu({width: 150});
});

</script>
{% endblock %}

get_together/templates/get_together/new_event/detail_event.html
{% extends "get_together/base.html" %}
{% load static i18n %}

{% block meta %}
<script type="text/javascript" src="{% static 'recurrence/js/recurrence.js' %}"></script>
<script type="text/javascript" src="{% static 'recurrence/js/recurrence-widget.js' %}"></script>
<link href="{% static 'recurrence/css/recurrence.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<h2>{% trans "Provide some more information about your event" %}</h2>

<form action="{% url "new-event-add-details" event.id %}" method="post">
{% csrf_token %}
<div class="form-group">
{% include "events/event_form.html" %}
	<br />
<button type="submit" class="btn btn-primary">{% trans "Save details" %}</button>
<a class="btn btn-secondary" href="{% url 'new-event-add-team' event.id %}">{% trans "Skip" %}</a>
</div>
</form>
{% endblock %}

get_together/templates/get_together/new_event/pick_team.html
{% extends "get_together/base.html" %}
{% load static i18n %}

{% block styles %}
    <link href="{% static 'css/bootstrap-album.css' %}" rel="stylesheet"/>
{% endblock %}

{% block content %}
<div class="container">
    {% if teams %}
    <div class="row">
        <div class="col-12">
            <center>
                <h3>{{ theme.text_labels.which_team_hosting }}</h3>
            </center>
        </div>
    </div>
    <form action="{% url 'new-event-add-team' event.id %}" method="POST">
        {% csrf_token %}
    <div class="row">
    {% for team in teams %}
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <div class="card-banner">
              {% if team.category %}
              <img class="card-img-top" src="{{team.category.img_url}}" alt="{{team.name}}">
              {% else %}
              <img class="card-img-top" src="{% static 'img/team_placeholder.png' %}" alt="{{team.name}}">
              {% endif %}
              <p class="card-title">{{team.name}}</p>
            </div>
            <div class="card-body">
              <p class="card-text"><strong>{{team.city}}</strong></p>
              <div class="d-flex justify-content-between align-items-center">
                <button class="btn btn-outline-primary" name="team_id" value="{{team.id}}" type="submit">{{ theme.text_labels.host_verb }}</button>
              </div>
            </div>
          </div>
        </div>
    {% endfor %}
    </div>
    </form>
    {% else %}
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <center>
                <h3>{% trans "You don't have any teams that can host this event, would you like to start one now?" %}</h3>
            </center>
        </div>
        <div class="col-2"></div>
    </div>
    {% endif %}
    <div class="row pb-5">
        <div class="col-12">
            <center>
                <a class="btn btn-success" href="{% url 'create-team' %}?event={{event.id}}">{% trans "Create a new Team" %}</a>
                <a class="btn btn-secondary" href="{{event.get_absolute_url}}">{{ theme.text_labels.host_as_myself }}</a>
            </center>
        </div>
    </div>
</div>
{% endblock %}