get_together/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from events import feeds, views as event_views

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("admin/", admin.site.urls),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path(
        "account/password_change/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "account/password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "account/password_reset/",
        views.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "account/password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "account/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "account/reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("searchables/", event_views.searchable_list, name="searchables"),
    path("api/places/", event_views.places_list),
    path("api/countries/", event_views.country_list),
    path("api/spr/", event_views.spr_list),
    path("api/cities/", event_views.city_list),
    path("api/find_city/", event_views.find_city),
    path("api/teams/", event_views.teams_list),
    path("api/org/<int:org_id>/", event_views.org_member_list),
    path("api/upcoming_events/", event_views.upcoming_events),
    path(
        "profile/+confirm_profile",
        views.setup_1_confirm_profile,
        name="setup-1-confirm-profile",
    ),
    path(
        "profile/+pick_categories",
        views.setup_2_pick_categories,
        name="setup-2-pick-categories",
    ),
    path("profile/+find_teams", views.setup_3_find_teams, name="setup-3-find-teams"),
    path(
        "profile/+attend_events",
        views.setup_4_attend_events,
        name="setup-4-attend-events",
    ),
    path("profile/+setup_complete", views.setup_complete, name="setup-complete"),
    path("profile/+edit", views.edit_profile, name="edit-profile"),
    path(
        "profile/+send_confirmation_email",
        views.user_send_confirmation_email,
        name="send-confirm-email",
    ),
    path(
        "profile/+confirm_email/<str:confirmation_key>",
        views.user_confirm_email,
        name="confirm-email",
    ),
    path(
        "profile/+confirm_notifications",
        views.user_confirm_notifications,
        name="confirm-notifications",
    ),
    path("profile/<int:user_id>/", views.show_profile, name="show-profile"),
    path(
        "profile/<str:account_secret>.ics",
        feeds.UserEventsCalendar(),
        name="user-event-ical",
    ),
    path("profile/+add-speaker", views.add_speaker, name="add-speaker"),
    path("speaker/<int:speaker_id>/", views.show_speaker, name="show-speaker"),
    path("speaker/<int:speaker_id>/+edit", views.edit_speaker, name="edit-speaker"),
    path(
        "speaker/<int:speaker_id>/+delete", views.delete_speaker, name="delete-speaker"
    ),
    path("profile/+talks", views.list_user_talks, name="user-talks"),
    path("profile/+add-talk", views.add_talk, name="add-talk"),
    path("talk/<int:talk_id>/", views.show_talk, name="show-talk"),
    path("talk/<int:talk_id>/+edit", views.edit_talk, name="edit-talk"),
    path("talk/<int:talk_id>/+delete", views.delete_talk, name="delete-talk"),
    path("events/", views.events_list, name="events"),
    path("events/all/", views.events_list_all, name="all-events"),
    path("teams/", views.teams_list, name="teams"),
    path("teams/all/", views.teams_list_all, name="all-teams"),
    path("team/<int:team_id>/", views.show_team_by_id, name="show-team"),
    path("team/<int:team_id>/+edit/", views.edit_team, name="edit-team"),
    path("team/<int:team_id>/+join/", event_views.join_team, name="join-team"),
    path("team/<int:team_id>/+leave/", event_views.leave_team, name="leave-team"),
    path("team/<int:team_id>/+delete/", views.delete_team, name="delete-team"),
    path("team/<int:team_id>/+members/", views.manage_members, name="manage-members"),
    path(
        "team/<int:team_id>/+change_role/<int:profile_id>/",
        views.change_member_role,
        name="change-member-role",
    ),
    path("team/<int:team_id>/+invite/", views.invite_members, name="invite-members"),
    path(
        "team/invite/<int:invite_id>/+resend/",
        views.resend_member_invite,
        name="resend-member-invite",
    ),
    path(
        "team/+accept_invite/<str:invite_key>/",
        views.confirm_request_to_join_team,
        name="accept-invite-to-join-team",
    ),
    path(
        "team/<int:team_id>/events.ics",
        feeds.TeamEventsCalendar(),
        name="team-event-ical",
    ),
    path(
        "team/<int:team_id>/<str:account_secret>/events.ics",
        feeds.PrivateTeamEventsCalendar(),
        name="private-team-event-ical",
    ),
    path("+create-team/", views.start_new_team, name="create-team"),
    path("team/<int:team_id>/+define/", views.define_new_team, name="define-team"),
    path(
        "team/+create-event/",
        views.create_event_team_select,
        name="create-event-team-select",
    ),
    path("team/<int:team_id>/+create-event/", views.create_event, name="create-event"),
    path("+new-event/", views.new_event_start, name="new-event-start"),
    path(
        "events/<int:event_id>/+new-event-place/",
        views.new_event_add_place,
        name="new-event-add-place",
    ),
    path(
        "events/<int:event_id>/+new-event-details/",
        views.new_event_add_details,
        name="new-event-add-details",
    ),
    path(
        "events/<int:event_id>/+new-event-team/",
        views.new_event_add_team,
        name="new-event-add-team",
    ),
    path("events/<int:event_id>/+edit/", views.edit_event, name="edit-event"),
    path("events/<int:event_id>/+host/", views.change_event_host, name="change-team"),
    path("events/<int:event_id>/+attend/", views.attend_event, name="attend-event"),
    path(
        "events/<int:event_id>/+attended/", views.attended_event, name="attended-event"
    ),
    path(
        "events/<int:event_id>/+attendees/",
        views.manage_attendees,
        name="manage-attendees",
    ),
    path(
        "events/<int:event_id>/+sponsors/",
        views.manage_event_sponsors,
        name="manage-event-sponsors",
    ),
    path("events/<int:event_id>/+sponsor/", views.sponsor_event, name="sponsor-event"),
    path(
        "events/<int:event_id>/+invite/",
        views.invite_attendees,
        name="invite-attendees",
    ),
    path("events/<int:event_id>/+delete/", views.delete_event, name="delete-event"),
    path("events/<int:event_id>/+cancel/", views.cancel_event, name="cancel-event"),
    path("events/<int:event_id>/+restore/", views.restore_event, name="restore-event"),
    path(
        "events/<int:event_id>/+add_place/", views.add_place_to_event, name="add-place"
    ),
    path("events/<int:event_id>/+comment/", views.comment_event, name="comment-event"),
    path("comment/<int:comment_id>/+edit/", views.edit_comment, name="comment-edit"),
    path(
        "comment/<int:comment_id>/+delete/", views.delete_comment, name="comment-delete"
    ),
    path(
        "events/<int:event_id>/+photo/", views.add_event_photo, name="add-event-photo"
    ),
    path(
        "photo/<int:photo_id>/+remove/",
        views.remove_event_photo,
        name="remove-event-photo",
    ),
    path(
        "events/<int:event_id>/+propose-talk/",
        views.propose_event_talk,
        name="propose-event-talk",
    ),
    path(
        "events/<int:event_id>/+schedule-talks/",
        views.schedule_event_talks,
        name="schedule-event-talks",
    ),
    path(
        "events/<int:event_id>/<str:event_slug>/", views.show_event, name="show-event"
    ),
    path(
        "events/<int:event_id>/<str:event_slug>.ics",
        feeds.SingleEventCalendar(),
        name="single-event-ical",
    ),
    path("series/<int:series_id>/+edit/", views.edit_series, name="edit-series"),
    path("series/<int:series_id>/+delete/", views.delete_series, name="delete-series"),
    path(
        "series/<int:series_id>/+add_place/",
        views.add_place_to_series,
        name="add-place-to-series",
    ),
    path(
        "series/<int:series_id>/<str:series_slug>/",
        views.show_series,
        name="show-series",
    ),
    path("org/<str:org_slug>/", views.show_org, name="show-org"),
    path("org/<str:org_slug>/+edit/", views.edit_org, name="edit-org"),
    path(
        "team/<int:team_id>/+invite_to_join_org/",
        views.invite_to_join_org,
        name="invite-to-join-org",
    ),
    path(
        "org/invite/<int:invite_id>/+resend/",
        views.resend_org_invite,
        name="resend-org-invite",
    ),
    path(
        "org/<str:org_slug>/+request_to_join_org/",
        views.request_to_join_org,
        name="request-to-join-org",
    ),
    path(
        "org/+confirm_request/<str:request_key>/",
        views.confirm_request_to_join_org,
        name="confirm-request-to-join-org",
    ),
    path(
        "org/<str:org_slug>/+manage_teams/", views.manage_org_teams, name="manage-teams"
    ),
    path(
        "org/<str:org_slug>/+create-event/",
        views.create_common_event,
        name="create-common-event",
    ),
    path(
        "common/<int:event_id>/+create-event/",
        views.create_common_event_team_select,
        name="create-common-event-team-select",
    ),
    path(
        "common/<int:event_id>/+edit/",
        views.edit_common_event,

events/models/locale.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

import pytz
from rest_framework import serializers


class Language(models.Model):
    class Meta:
        ordering = ("name",)

    name = models.CharField(_("Language"), max_length=150, null=True)
    code = models.CharField(_("Language Code"), max_length=20, null=True)

    def __str__(self):
        return u"%s" % (self.name)


class Continent(models.Model):
    name = models.CharField(_("Name"), max_length=50)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return u"%s" % (self.name)


class Country(models.Model):
    name = models.CharField(_("Name"), max_length=100)
    code = models.CharField(_("Country Code"), max_length=8)
    continents = models.ManyToManyField(Continent)

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Countries"

    def __str__(self):
        return u"%s" % (self.name)

    @property
    def slug(self):
        if self.name is not None:
            return self.name.replace(",", "").replace(" ", "_")
        else:
            return "no_country"


class CountrySerializer(serializers.ModelSerializer):
    display = serializers.CharField(source="__str__", read_only=True)

    class Meta:
        model = Country
        fields = ("id", "name", "code", "display")


class SPR(models.Model):
    name = models.CharField(_("Name"), max_length=100)
    code = models.CharField(_("Admin Code"), max_length=8)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return u"%s, %s" % (self.name, self.country.name)

    @property
    def slug(self):
        if self.name is not None:
            return self.name.replace(",", "").replace(" ", "_")
        else:
            return "no_spr"


class SPRSerializer(serializers.ModelSerializer):
    display = serializers.CharField(source="__str__", read_only=True)

    class Meta:
        model = SPR
        fields = ("id", "name", "code", "country", "slug", "display")


class City(models.Model):
    class Meta:
        ordering = ("name",)
        verbose_name_plural = _("Cities")

    name = models.CharField(_("Name"), max_length=100)
    spr = models.ForeignKey(SPR, on_delete=models.CASCADE)
    tz = models.CharField(
        max_length=32,
        verbose_name=_("Default Timezone"),
        default="UTC",
        choices=[(tz, tz) for tz in pytz.all_timezones],
        blank=False,
        null=False,
        help_text=_("The most commonly used timezone for this Team."),
    )
    longitude = models.FloatField(
        help_text=_("Longitude in Degrees East"), null=True, blank=True
    )
    latitude = models.FloatField(
        help_text=_("Latitude in Degrees North"), null=True, blank=True
    )
    population = models.IntegerField(
        help_text=_("Population"), null=False, blank=False, default=0
    )

    @property
    def short_name(self):
        if self.spr.country.name == "United States":
            return u"%s, %s" % (self.name, self.spr.name)
        else:
            return u"%s, %s" % (self.name, self.spr.country.name)

    def __str__(self):
        return u"%s, %s, %s" % (self.name, self.spr.name, self.spr.country.name)

    @property
    def slug(self):
        if self.name is not None:
            return self.name.replace(",", "").replace(" ", "_")
        else:
            return "no_city"


class CitySerializer(serializers.ModelSerializer):
    display = serializers.CharField(source="__str__", read_only=True)

    class Meta:
        model = City
        fields = (
            "id",
            "name",
            "short_name",
            "spr",
            "tz",
            "latitude",
            "longitude",
            "slug",
            "display",
        )

events/models/speakers.py
import datetime

from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

import pytz
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

from .. import location
from ..utils import slugify
from .events import *
from .locale import *
from .profiles import *
from .search import *


class Speaker(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    avatar = ProcessedImageField(
        verbose_name=_("Photo Image"),
        upload_to="avatars",
        processors=[ResizeToFill(128, 128)],
        format="PNG",
        blank=True,
    )
    title = models.CharField(max_length=256, blank=True, null=True)
    bio = models.TextField(verbose_name=_("Biography"), blank=True)

    categories = models.ManyToManyField("Category", blank=True)
    topics = models.ManyToManyField("Topic", blank=True)

    def headshot(self):
        if self.avatar:
            return self.avatar
        else:
            return self.user.avatar

    def headshot_url(self):
        if (
            self.avatar is not None
            and self.avatar.name is not None
            and self.avatar.name != ""
        ):
            return self.avatar.url
        else:
            return self.user.avatar_url()

    def __str__(self):
        if self.title is not None and self.title != "":
            return "%s, %s" % (self.user, self.title)
        else:
            return str(self.user)


class Talk(models.Model):
    PRESENTATION = 0
    WORKSHOP = 1
    PANEL = 2
    ROUNDTABLE = 3
    QANDA = 4
    DEMO = 5
    TYPES = [
        (PRESENTATION, _("Presentation")),
        (WORKSHOP, _("Workshop")),
        (PANEL, _("Panel")),
        (ROUNDTABLE, _("Roundtable")),
        (QANDA, _("Q & A")),
        (DEMO, _("Demonstration")),
    ]
    speaker = models.ForeignKey(
        Speaker,
        verbose_name=_("Speaker Bio"),
        related_name="talks",
        on_delete=models.CASCADE,
    )
    title = models.CharField(max_length=256)
    abstract = models.TextField()
    talk_type = models.SmallIntegerField(_("Type"), choices=TYPES, default=PRESENTATION)
    web_url = models.URLField(_("Website"), null=True, blank=True)

    category = models.ForeignKey(
        "Category", on_delete=models.SET_NULL, blank=False, null=True
    )
    topics = models.ManyToManyField("Topic", blank=True)

    @property
    def future_presentations(self):
        return self.presentations.filter(
            status__gte=0, event__start_time__gt=timezone.now()
        )

    @property
    def past_presentations(self):
        return self.presentations.filter(
            status=1, event__start_time__lte=timezone.now()
        )

    def __str__(self):
        self.title


class SpeakerRequest(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    topics = models.ManyToManyField("Topic", blank=True)


class Presentation(models.Model):
    DECLINED = -1
    PROPOSED = 0
    ACCEPTED = 1

    STATUSES = [
        (DECLINED, _("Declined")),
        (PROPOSED, _("Proposed")),
        (ACCEPTED, _("Accepted")),
    ]
    event = models.ForeignKey(
        Event, related_name="presentations", on_delete=models.CASCADE
    )
    talk = models.ForeignKey(
        Talk,
        related_name="presentations",
        on_delete=models.CASCADE,
        blank=False,
        null=True,
    )
    status = models.SmallIntegerField(choices=STATUSES, default=PROPOSED, db_index=True)
    start_time = models.DateTimeField(
        verbose_name=_("Start Time"), db_index=True, null=True, blank=True
    )

    created_by = models.ForeignKey(
        UserProfile, on_delete=models.SET_NULL, null=True, blank=False
    )
    created_time = models.DateTimeField(default=timezone.now, db_index=True)

    def __str__(self):
        try:
            return "%s at %s" % (self.talk.title, self.event.name)
        except:
            return _("No talk")

get_together/templates/get_together/speakers/create_speaker.html
{% extends "get_together/base.html" %}
{% load static i18n %}


{% block content %}
<h2>{% trans "New Speaker Bio" %}</h2>


<form enctype="multipart/form-data" action="{% url "add-speaker" %}" method="post">
{% csrf_token %}
<div class="form-group">
    <table class="table">
        <tr><th></th><td><img src="{% if speaker.headshot %}{{speaker.headshot.url}}{% endif %}"/></td></tr>
        {{speaker_form}}
    </table>
	<br />
<button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
</div>
</form>
{% endblock %}

get_together/templates/get_together/speakers/create_talk.html
{% extends "get_together/base.html" %}
{% load static i18n %}


{% block content %}
<h2>{% trans "New Talk" %}</h2>


<form action="{% url "add-talk" %}" method="post">
{% csrf_token %}
{% if event %}<input type="hidden" name="event" value="{{event.id}}" />{% endif %}

<div class="form-group">
    <table class="table">
        {{talk_form}}
    </table>
	<br />
<button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
</div>
</form>
{% endblock %}


{% block javascript %}
<script type="text/javascript">
$(document).ready(function(){

    $("#id_speaker").selectmenu()
    $("#id_talk_type").selectmenu()
    $("#id_category").selectmenu()
});
</script>
{% endblock %}

get_together/templates/get_together/speakers/delete_speaker.html
{% extends "get_together/base.html" %}
{% load i18n %}

{% block content %}
<h2>{% trans "Confirm deletion" %}</h2>
{% if speaker.talks.count > 0 %}
    <div class="alerts">
        <div class="alert alert-danger">
            {% blocktrans count talk_count=speaker.talks.count %}
            This speaker profile has {{ talk_count }} talk!
            {% plural %}
            This speaker profile has {{ talk_count }} talks!
            {% endblocktrans %}
        </div>
    </div>
{% endif %}
{% blocktrans with speaker_title=speaker.title %}Are you sure you want to delete <strong>{{speaker_title}}</strong>?{% endblocktrans %}
<form action="{% url "delete-speaker" speaker.id %}" method="post">
{% csrf_token %}
<div class="form-group">
{{ delete_form }}
	<br />
<button type="submit" class="btn btn-danger">{% trans "Delete Talk" %}</button>
</div>
</form>
{% endblock %}

get_together/templates/get_together/speakers/delete_talk.html
{% extends "get_together/base.html" %}
{% load i18n %}

{% block content %}
<h2>{% trans "Confirm deletion" %}</h2>
{% if talk.future_presentations.count > 0 %}
    <div class="alerts">
        <div class="alert alert-danger">{% blocktrans with event_count=talk.future_presentations.count %}This talk has {{ event_count }} pending events!{% endblocktrans %}</div>
    </div>
{% endif %}
{% blocktrans with talk_title=talk.title %}Are you sure you want to delete <strong>{{talk_title}}</strong>?{% endblocktrans %}
<form action="{% url "delete-talk" talk.id %}" method="post">
{% csrf_token %}
<div class="form-group">
{{ delete_form }}
	<br />
<button type="submit" class="btn btn-danger">{% trans "Delete Talk" %}</button>
</div>
</form>
{% endblock %}

get_together/templates/get_together/speakers/edit_speaker.html
{% extends "get_together/base.html" %}
{% load static i18n %}


{% block content %}
<h2>{% trans "Edit Speaker" %}</h2>


<form enctype="multipart/form-data" action="{% url "edit-speaker" speaker.id %}" method="post">
{% csrf_token %}
<div class="form-group">
    <table class="table">
        <tr><th></th><td><img src="{{speaker.headshot_url}}"/></td></tr>
        {{speaker_form}}
    </table>
	<br />
<button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
</div>
</form>
<a href="{% url 'delete-speaker' speaker.id %}" class="btn btn-danger">{% trans "Delete" %}</a>

{% endblock %}

{% block javascript %}
<script type="text/javascript">
$(document).ready(function(){
    $("#city_select").lookup({
        search: function(searchText, callback) {
            if (searchText.length < 3) return callback(searchText, []);
            $.getJSON("/api/cities/?q="+searchText, function(data) {
                var m = this.url.match(/q=([^&]+)/);
                var q = "";
                if (m && m.length > 0) {
                    q = this.url.match(/q=([^&]+)/)[1]
                }

                return callback(q, data);
            });
        },
        select: function( event, ui ) {
          $("#id_tz").val(ui.data.tz);
          $("#id_tz").selectmenu("refresh");
        }
    });
    $("#id_categories").selectmenu()
});
</script>
{% endblock %}

get_together/templates/get_together/speakers/edit_talk.html
{% extends "get_together/base.html" %}
{% load static i18n %}


{% block content %}
<h2>{% trans "Edit Talk" %}</h2>


<form action="{% url "edit-talk" talk.id %}" method="post">
{% csrf_token %}
<div class="form-group">
    <table class="table">
        {{talk_form}}
    </table>
	<br />
<button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
</div>
</form>
<a href="{% url 'delete-talk' talk.id %}" class="btn btn-danger">{% trans "Delete" %}</a>

{% endblock %}

{% block javascript %}
<script type="text/javascript">
$(document).ready(function(){

    $("#id_speaker").selectmenu()
    $("#id_talk_type").selectmenu()
    $("#id_category").selectmenu()
});
</script>
{% endblock %}

get_together/templates/get_together/speakers/list_user_presentations.html
{% extends "get_together/base.html" %}
{% load static tz i18n %}

{% block styles %}
    <link href="{% static 'css/bootstrap-album.css' %}" rel="stylesheet"/>

{% endblock %}

{% block content %}
        <div class="container">
{% if not has_talks %}
            <div class="alert alert-warning">{% trans "You must create a talk before it can be proposed to this event." %}</div>
{% endif %}

{% if proposed_talks %}
        <div class="row">
{% for presentation in proposed_talks %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow" style="width: 18rem;">
                <div class="card-body">
                  <p class="card-title" style="height: 2rem;">
                      <strong><a href="{% url 'show-talk' presentation.talk.id %}">{{presentation.talk.title}}</a></strong>
                    {% if presentation.status == -1 %}
                        <span class="badge badge-danger" >{% trans "Declined" %}</span>
                    {% elif presentation.status == 1 %}
                        <span class="badge badge-success" >{% trans "Accepted" %}</span>
                    {% else %}
                        <span class="badge badge-info" >{% trans "Submitted" %}</span>
                    {% endif %}
                  </p>
                  <div class="card-text">
                    <small class="text-muted mb-1">{{ presentation.talk.speaker }}</small>
                  </div>
                </div>
              </div>
            </div>
{% endfor %}
        </div>
        <hr/>
{% endif %}
        <div class="row">
{% for talk in available_talks %}
            <form action="{% url 'propose-event-talk' event.id %}" method="POST">
            {% csrf_token %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow" style="width: 18rem;">
                <div class="card-body">
                  <p class="card-title" style="height: 2rem;"><strong><a href="{% url 'show-talk' talk.id %}">{{talk.title}}</a></strong></p>
                  <div class="card-text">
                    <small class="text-muted mb-1">{{ talk.speaker }}</small>
                    <button class="btn btn-primary" type="submit" name="talk_id" value="{{talk.id}}">{% trans "Propose" %}</a></span>
                  </div>
                </div>
              </div>
            </div>
            </form>
{% endfor %}
        </div>
        <div class="row">
            <div class="col">
                <a href="{{event.get_absolute_url}}" class="btn btn-secondary">{% trans "Cancel" %}</a>
                <a href="{% url 'add-talk' %}?event={{event.id}}" class="btn btn-success">{% trans "New Talk" %}</a>
            </div>
        </div>
    </div>

{% endblock %}

get_together/templates/get_together/speakers/list_user_talks.html
{% extends "get_together/base.html" %}
{% load static tz i18n %}

{% block styles %}
    <link href="{% static 'css/bootstrap-album.css' %}" rel="stylesheet"/>

{% endblock %}

{% block content %}
        <div class="container-fluid">
        <div class="row">
{% for speaker in speaker_bios %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow" style="width: 18rem;">
                <div class="card-img-top mt-1" style="text-align: center"><img src="{{speaker.headshot_url}}"/></div>
                <div class="card-body">
                  <p class="card-title" style="height: 2rem;">
                      <strong><a href="{% url 'edit-speaker' speaker.id %}">{{speaker.title}}</a></strong>
                  </p>
                  <div class="card-text">
                    <small class="text-muted mb-1">{{ speaker.bio }}</small>
                  </div>
                </div>
              </div>
            </div>
{% endfor %}
        </div>
        <div class="row">
            <div class="col">
                <a href="{% url 'add-speaker' %}" class="btn btn-success"><i class="fa fa-plus"></i> {% trans "Speaker Bio" %}</a>
            </div>
        </div>
        <hr/>

        <div class="row">
{% for talk in talks %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow" style="width: 18rem;">
                <div class="card-body">
                  <p class="card-title" style="height: 2rem;"><strong><a href="{% url 'edit-talk' talk.id %}">{{talk.title}}</a></strong></p>
                  <div class="card-text">
                    <small class="text-muted mb-1">{{ talk.abstract }}</small>
                  </div>
                </div>
              </div>
            </div>
{% endfor %}
        </div>
        <div class="row">
            <div class="col">
                <a href="{% url 'add-talk' %}" class="btn btn-success"><i class="fa fa-plus"></i> {% trans "Talk" %}</a>
            </div>
        </div>
    </div>

{% endblock %}

get_together/templates/get_together/speakers/show_speaker.html
{% extends "get_together/base.html" %}
{% load markup static i18n %}

{% block styles %}
    <link href="{% static 'css/bootstrap-album.css' %}" rel="stylesheet"/>

{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <img src="{{speaker.headshot_url}}"/>                
            {% if speaker.user == request.user.profile %}
            <a href="{% url 'edit-speaker' speaker.id %}" class="btn btn-secondary btn-sm">{% trans "Edit Bio" %}</a>
            {% endif %}
            <hr/>
            <h3>{{ speaker.user }}</h3>
            {% if speaker.title %}<h5 class="text-muted">{{ speaker.title }}</h5>{% endif %}
            <p>
                {{ speaker.bio|markdown }}
            </p>

{% if talks %}
        <br/>
        <h4>{% trans "Talks" %}</h4>
        <div class="container">
        <div class="row">
        {% for talk in talks %}
            <div class="col-md-4">
              <div class="card box-shadow" >
                <div class="card-body">
                  <p class="card-title"><strong><a href="{% url 'show-talk' talk.id %}">{{talk.title}}</a></strong></p>
                  <div class="card-text">
                    <small class="text-muted mb-1">{{ talk.speaker }}</small>
                  </div>
                </div>
              </div>
            </div>
        {% endfor %}
        </div>
        </div>
{% endif %}
        </div>
        <div class="col-md-3">
            <div class="container">
                <div class="row">
                    <div class="col"><h4>{% trans "Events" %} ({{presentations.count}})</h4><hr/></div>
                </div>
                {% for presentation in presentations %}
                <div class="row mb-3">
                    <div class="col">
                        <h6 class="mt-2 mb-0"><a href="{{presentation.event.get_absolute_url}}">{{presentation.event.name}}</a></h6>
                        <small>{{ presentation.event.team }}</small><br/>
                        <small class="text-muted">{{ presentation.event.local_start_time }}</small>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

    </div>
</div>
{% endblock %}